#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANDROID = ROOT / 'android'
if not ANDROID.exists():
    raise SystemExit('android/ was not generated by Capacitor')

main_files = list((ANDROID / 'app' / 'src' / 'main' / 'java').rglob('MainActivity.java'))
if not main_files:
    raise SystemExit('MainActivity.java not found after cap sync')
main = main_files[0]
package_line = next((line for line in main.read_text(encoding='utf-8').splitlines() if line.startswith('package ')), None)
if not package_line:
    raise SystemExit('Could not determine MainActivity package')
package_name = package_line.split()[1].rstrip(';')

bridge = main.parent / 'ResuMateNativeBridge.java'
bridge.write_text(r'''package __PACKAGE__;

import android.Manifest;
import android.app.Activity;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.ContentResolver;
import android.content.ContentValues;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.provider.MediaStore;
import android.util.Base64;
import android.webkit.JavascriptInterface;
import android.webkit.WebView;

import androidx.core.app.NotificationCompat;
import androidx.core.app.NotificationManagerCompat;
import com.getcapacitor.BridgeActivity;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;

/** Native Android bridge for ResuMate exports and download notifications. */
public final class ResuMateNativeBridge {
    private static final String CHANNEL_ID = "resumate_downloads";
    private static final int NOTIFICATION_PERMISSION_REQUEST = 7001;
    private ResuMateNativeBridge() {}

    public static void install(Activity activity) {
        if (!(activity instanceof BridgeActivity)) return;
        BridgeActivity ba = (BridgeActivity) activity;
        createChannel(activity);
        WebView webView = ba.getBridge().getWebView();
        if (webView == null) return;
        webView.addJavascriptInterface(new NativeApi(activity), "ResuMateNative");
        if (Build.VERSION.SDK_INT >= 33 && activity.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED) {
            activity.requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS}, NOTIFICATION_PERMISSION_REQUEST);
        }
    }

    private static void createChannel(Context context) {
        if (Build.VERSION.SDK_INT >= 26) {
            NotificationManager nm = context.getSystemService(NotificationManager.class);
            if (nm != null) nm.createNotificationChannel(new NotificationChannel(CHANNEL_ID, "ResuMate Downloads", NotificationManager.IMPORTANCE_DEFAULT));
        }
    }

    private static final class NativeApi {
        private final Activity activity;
        NativeApi(Activity activity) { this.activity = activity; }

        @JavascriptInterface
        public String saveBase64File(String fileName, String mimeType, String base64) {
            try {
                String safe = fileName == null ? "Resume" : fileName.replaceAll("[^a-zA-Z0-9._-]", "_");
                if (safe.length() == 0) safe = "Resume";
                byte[] bytes = Base64.decode(base64, Base64.DEFAULT);
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                    ContentResolver resolver = activity.getContentResolver();
                    ContentValues values = new ContentValues();
                    values.put(MediaStore.Downloads.DISPLAY_NAME, safe);
                    values.put(MediaStore.Downloads.MIME_TYPE, mimeType == null ? "application/octet-stream" : mimeType);
                    values.put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS + "/ResuMate/Resumes");
                    values.put(MediaStore.Downloads.IS_PENDING, 1);
                    Uri uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values);
                    if (uri == null) return "ERROR:Unable to create Downloads/ResuMate/Resumes file";
                    try (OutputStream out = resolver.openOutputStream(uri)) {
                        if (out == null) throw new IllegalStateException("Unable to open destination");
                        out.write(bytes);
                    } catch (Exception e) {
                        resolver.delete(uri, null, null);
                        throw e;
                    }
                    ContentValues done = new ContentValues();
                    done.put(MediaStore.Downloads.IS_PENDING, 0);
                    resolver.update(uri, done, null, null);
                    return "OK:" + uri;
                }
                File downloads = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
                File dir = new File(downloads, "ResuMate/Resumes");
                if (!dir.exists() && !dir.mkdirs()) return "ERROR:Unable to create Downloads/ResuMate/Resumes";
                File target = new File(dir, safe);
                try (FileOutputStream out = new FileOutputStream(target)) { out.write(bytes); }
                return "OK:file://" + Uri.fromFile(target);
            } catch (Exception e) {
                return "ERROR:" + (e.getMessage() == null ? e.getClass().getSimpleName() : e.getMessage());
            }
        }

        @JavascriptInterface
        public void notifyDownload(String fileName, String mimeType, String uriString) {
            try {
                Uri uri = Uri.parse(uriString);
                Intent view = new Intent(Intent.ACTION_VIEW);
                view.setDataAndType(uri, mimeType == null ? "application/octet-stream" : mimeType);
                view.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_ACTIVITY_NEW_TASK);
                PendingIntent pending = PendingIntent.getActivity(activity, Math.abs((fileName == null ? "file" : fileName).hashCode()), view, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
                NotificationCompat.Builder b = new NotificationCompat.Builder(activity, CHANNEL_ID)
                        .setSmallIcon(android.R.drawable.stat_sys_download_done)
                        .setContentTitle("ResuMate download complete")
                        .setContentText((fileName == null ? "Resume" : fileName) + " saved to Downloads/ResuMate/Resumes")
                        .setAutoCancel(true)
                        .setContentIntent(pending)
                        .setPriority(NotificationCompat.PRIORITY_DEFAULT);
                if (Build.VERSION.SDK_INT < 33 || activity.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS) == PackageManager.PERMISSION_GRANTED) {
                    NotificationManagerCompat.from(activity).notify(Math.abs((fileName == null ? "file" : fileName).hashCode()), b.build());
                }
            } catch (Exception ignored) { }
        }
    }
}
'''.replace('__PACKAGE__', package_name), encoding='utf-8')

manifest = ANDROID / 'app' / 'src' / 'main' / 'AndroidManifest.xml'
if manifest.exists():
    mt = manifest.read_text(encoding='utf-8')
    perm = '    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />\n'
    if 'android.permission.POST_NOTIFICATIONS' not in mt:
        idx = mt.find('>', mt.find('<manifest'))
        if idx >= 0:
            mt = mt[:idx+1] + '\n' + perm + mt[idx+1:]
        manifest.write_text(mt, encoding='utf-8')

text = main.read_text(encoding='utf-8')
if 'ResuMateNativeBridge.install(this);' not in text:
    if 'import android.os.Bundle;' not in text:
        text = text.replace(package_line + '\n', package_line + '\n\nimport android.os.Bundle;\n', 1)
    insert = '''\n    @Override\n    public void onCreate(Bundle savedInstanceState) {\n        super.onCreate(savedInstanceState);\n        ResuMateNativeBridge.install(this);\n    }\n\n    @Override\n    public void onBackPressed() {\n        if (getBridge() != null && getBridge().getWebView() != null) {\n            getBridge().getWebView().evaluateJavascript(\"window.smartBack&&window.smartBack()\", null);\n        } else {\n            super.onBackPressed();\n        }\n    }\n'''
    pos = text.rfind('}')
    text = text[:pos] + insert + text[pos:]
    main.write_text(text, encoding='utf-8')
print(f'Patched native bridge: {main}')
